Add test and code coverage report

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,12 +1,13 @@
-# This is a basic workflow to build robot code.
-# Copied from https://docs.wpilib.org/en/stable/docs/software/advanced-gradlerio/robot-code-ci.html
-
 name: CI
 
+permissions:
+  checks: write
+  pull-requests: write
+
 # Controls when the action will run. Triggers the workflow on push or pull request
-# events but only for the main branch.
 on:
   push:
+  pull_request:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -22,6 +23,8 @@ jobs:
     steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v4
+      with:
+        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
 
     # Declares the repository safe and not under dubious ownership.
     - name: Add repository to git safe directories
@@ -30,7 +33,36 @@ jobs:
     # Grant execute permission for gradlew
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
-
-    # Runs a single command using the runners shell
+    - name: Cache SonarQube packages
+      uses: actions/cache@v4
+      with:
+        path: ~/.sonar/cache
+        key: ${{ runner.os }}-sonar
+        restore-keys: ${{ runner.os }}-sonar
+    - name: Cache Gradle packages
+      uses: actions/cache@v4
+      with:
+        path: ~/.gradle/caches
+        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
+        restore-keys: ${{ runner.os }}-gradle
+    # Run tests and generate code coverage report
     - name: Compile robot code
       run: ./gradlew build
+    - name: Run Tests
+      run: ./gradlew test
+      continue-on-error: true
+    - name: Generate JaCoCo Report
+      run: ./gradlew jacocoTestReport
+    # Publish reports and analysis
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v5
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: "**/build/test-results/test/TEST-*.xml"
+        comment: true
+    - name: SonarCloud Code Analysis
+      if: success() || failure() # always run even if the previous step fails
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      run: ./gradlew sonar
